// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/career-theme/CurrentTheme.tsx": () => import("../components/mockups/career-theme/CurrentTheme.tsx"),
  "./components/mockups/career-theme/MidnightClarity.tsx": () => import("../components/mockups/career-theme/MidnightClarity.tsx")
};
